on: [push, workflow_dispatch]

name: wehoop WNBA Data trigger

jobs:
    wehoop_wnba_data_trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger wehoop WNBA Data
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ secrets.SDV_GH_TOKEN }}
                  repository: sportsdataverse/wehoop-wnba-data
                  event-type: daily_wnba_data
                  client-payload: |-
                    {
                      "ref": "refs/heads/main",
                      "event_name": "daily_wnba_data",
                      "commit_message": "${{ github.event.head_commit.message }}"
                    }
